spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.int[1,50]}

spring.rabbitmq.addresses=amqps://hirnkuvb:elpeiJdPIXt0Un3ydocrnuTtLQnoIlZP@jaragua.lmq.cloudamqp.com/hirnkuvb

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mpmiguel2007@gmail.com
spring.mail.password=qtea amnv zyub kjaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
