spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos
spring.datasource.username=postgres
spring.datasource.password=2007
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.show-sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.client.registry-fetch-interval-seconds=5
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.int[1,50]}

resilience4j.circuitbreaker.instances.verificaAutorizacao.slidingWindowSize=3

resilience4j.circuitbreaker.instances.verificaAutorizacao.slidingWindowType=COUNT_BASED

resilience4j.circuitbreaker.instances.verificaAutorizacao.minimumNumberOfCalls=5

resilience4j.circuitbreaker.instances.verificaAutorizacao.waitDurationInOpenState= 10s

spring.rabbitmq.addresses=amqps://hirnkuvb:elpeiJdPIXt0Un3ydocrnuTtLQnoIlZP@jaragua.lmq.cloudamqp.com/hirnkuvb
