spring.application.name=config-server

server.port=${PORT:8888}
spring.cloud.config.server.git.uri=${URI:https://github.com/zeus-crf/config-server}
spring.cloud.config.server.git.username=zeus-crf
spring.cloud.config.server.git.password=miguel2007

logging.level.org.springframework.cloud.config=DEBUG
logging.level.org.eclipse.jgit=DEBUG